README.md

docs: fix the package name

---

default-2.json

https://github.com/suzuki-shunsuke/aqua/pull/334

feat: add default-2 temporarily

---

default.json

Follow up #38
✅ Test: https://github.com/suzuki-shunsuke/aqua-registry/pull/322
https://github.com/suzuki-shunsuke/aqua/pull/334

feat: support new syntax

---

default.json

https://github.com/aquaproj/aqua-renovate-config/issues/84

fix: exclude space from tag

---

default.json
kubernetes-sigs-kustomize.json

Follow up #91
https://github.com/suzuki-shunsuke/test-renovate/pull/128

fix: fix updating kubernetes-sigs/kustomize

---

README.md
default.json
golang-go.json

support updating golang/go
https://github.com/golang/go
e.g. https://github.com/suzuki-shunsuke/test-renovate/pull/129

feat: support updating `golang/go`

---

README.md
default.json
kubernetes-kubectl.json

https://github.com/kubernetes/kubectl
https://github.com/suzuki-shunsuke/test-renovate/pull/130

feat: suppport kubernetes/kubectl

---

README.md
default.json

https://github.com/aquaproj/aqua-registry/pull/3049
👍 It works well. https://github.com/suzuki-shunsuke/test-renovate/pull/135
https://github.com/suzuki-shunsuke/test-renovate/blob/ab2fae95d8cf335e76ce01250970f40007709c62/renovate.json#L4

feat: support grpc/grpc-go/protoc-gen-go-grpc

---

default.json

https://github.com/orf/gping
https://github.com/aquaproj/aqua-registry/pull/3159
It works well.
https://github.com/suzuki-shunsuke/test-renovate/pull/142

feat: support orf/gping

---

default.json
golang-go.json

It works well.
https://github.com/suzuki-shunsuke/test-renovate/pull/145

feat(golang/go): support the prefix "go"

---

default.json
file.json

It works good. https://github.com/suzuki-shunsuke/test-renovate/pull/146

feat: support updating gopls

---

default.json
file.json

* https://github.com/aquaproj/aqua-renovate-config/issues/189#issuecomment-1204763479
* https://github.com/aquaproj/aqua-renovate-config/issues/189#issuecomment-1204769715

fix: distinguish go and github_release datasource by regular expression

---

file.json

https://github.com/aquaproj/aqua-renovate-config/issues/211

fix: revert the update of file.json by #207

---

default.json

Update renovate config for gcloud updates.
Ref: https://github.com/aquaproj/aqua-registry/pull/5742
Signed-off-by: Noel Georgi <git@frezbo.dev>

feat: renovate config for gcloud updates

---

default.json
file.json

https://github.com/oven-sh/bun

feat(oven-sh/bun): support updating bun

---

default.json

- https://github.com/aquaproj/aqua-registry/pull/8689

feat: support ipinfo/cli

---

default.json

Close https://github.com/aquaproj/aqua-renovate-config/issues/263

feat: support mongodb/mongodb-atlas-cli/atlascli

---

base.json
default.json
file.json
jsonnet/utils.libsonnet

https://github.com/aquaproj/aqua-renovate-config/pull/289#issuecomment-1364474527

fix: revert #289. Exclude a period from github-releases' depName

---

default.json
file.json
jsonnet/utils.libsonnet

Reverts aquaproj/aqua-renovate-config#304
I found a bug. https://github.com/aquaproj/test-aqua-renovate-config/pull/93

Revert "fix: fix the packageName of kubectl-convert"

---

default.json
file.json
jsonnet/utils.libsonnet

fix: fix kubectl-convert packageNameTemplate

---

base.json
default.json
file.json
golang-go.json
jsonnet/utils.libsonnet
kubernetes-kubectl.json
kubernetes-sigs-kustomize.json

feat: support updating digest

---

base.json
default.json
file.json
golang-go.json
jsonnet/utils.libsonnet
kubernetes-kubectl.json
kubernetes-sigs-kustomize.json

Reverts aquaproj/aqua-renovate-config#310
https://github.com/aquaproj/aqua-renovate-config/pull/310#issuecomment-1365099922

Revert "feat: support updating digest"

---

default.json
jsonnet/utils.libsonnet

Close https://github.com/aquaproj/aqua-renovate-config/issues/336

fix: resolve the deprecation warning of matchPaths

---

default.json
file.json
jsonnet/utils.libsonnet

- https://github.com/orgs/aquaproj/discussions/2016
- https://github.com/aquaproj/aqua-renovate-config/issues/406

feat: support crates.io

---

default.json
jsonnet/default.jsonnet

Looks good.
- https://github.com/suzuki-shunsuke/test-circleci/pull/23

feat: update aqua_version in .circleci/config.yml

---

default.json
file.json
jsonnet/utils.libsonnet

Close https://github.com/aquaproj/aqua-renovate-config/issues/421

feat: support awslabs/mountpoint-s3

---

default.json
file.json
jsonnet/utils.libsonnet

close #429 
test: https://github.com/mikutas/dotfiles/pull/391/files

feat: support jqlang/jq

---

default.json
jsonnet/utils.libsonnet

feat: support aws/aws-cli

---

default.json
file.json
jsonnet/utils.libsonnet

- https://github.com/aquaproj/aqua-registry/issues/13989#issuecomment-1802998523
- https://github.com/aquaproj/aqua-registry/pull/17141
Works well.
- https://github.com/suzuki-shunsuke/test-renovate/pull/238

feat: support trunk-io/launcher

---

jsonnet/default.jsonnet

Follow up https://github.com/aquaproj/aqua-renovate-config/pull/449

refactor: refactor

---

action.json
aqua-renovate-config.json
base.json
default.json
file.json
golang-go.json
installer-script.json
jsonnet/aqua-renovate-config.jsonnet
jsonnet/base.jsonnet
jsonnet/default.jsonnet
jsonnet/file.jsonnet
jsonnet/golang-go.jsonnet
jsonnet/installer-script.jsonnet
jsonnet/kubernetes-kubectl.jsonnet
jsonnet/kubernetes-sigs-kustomize.jsonnet
jsonnet/utils.libsonnet
kubernetes-kubectl.json
kubernetes-sigs-kustomize.json
renovate.json5

- https://github.com/renovatebot/renovate/pull/24451
- https://github.com/renovatebot/renovate/issues/19066

fix: migrate regexManagers to customManagers

---

default.json
file.json
jsonnet/utils.libsonnet

- https://github.com/suzuki-shunsuke/test-renovate/pull/256
- https://github.com/suzuki-shunsuke/test-renovate/pull/257

feat: support GitLab

---

default.json
file.json
jsonnet/utils.libsonnet

- https://github.com/aquaproj/aqua/issues/1359
- https://github.com/suzuki-shunsuke/test-renovate/pull/258
- https://github.com/suzuki-shunsuke/test-renovate/pull/261
- https://github.com/suzuki-shunsuke/test-renovate/pull/260

feat: support Gitea

---

default.json
installer-script.json
jsonnet/default.jsonnet
jsonnet/installer-script.jsonnet

https://github.com/renovatebot/renovate/discussions/28150#discussioncomment-8925362

fix: change versioningTemplate to versioning

---

default.json
jsonnet/default.jsonnet

fix: fix the support of devcontainer

---

base.json
default.json
file.json
jsonnet/utils.libsonnet

- https://github.com/aquaproj/aqua/issues/3267

feat: support updating go modules using go datasource

---

default.json
file.json
jsonnet/utils.libsonnet

close #705 
- https://github.com/mikutas/dotfiles/blob/542c98fde87b7c506a7a03910af3875785525e67/renovate.json5#L29-L46
- https://github.com/mikutas/dotfiles/pull/1368

feat: support updating Bitwarden CLI

---

default.json
file.json
jsonnet/utils.libsonnet

- https://github.com/aquaproj/aqua-registry/issues/29674

feat: support apache/maven

---

default.json
file.json
jsonnet/utils.libsonnet

- https://github.com/aquaproj/aqua-registry/pull/31762

feat: support external-secrets/external-secrets/esoctl

---

default.json
jsonnet/default.jsonnet

- https://github.com/renovatebot/renovate/pull/22406

fix: replace matchPaths with matchFileNames

---

default.json
jsonnet/default.jsonnet
jsonnet/file.jsonnet

fix: configure allowedVersions of protoc-gen-go-grpc

---

.github/workflows/autofix.yaml
.github/workflows/workflow_call_test.yaml

- https://github.com/renovatebot/renovate/discussions/35787#discussioncomment-13068531

ci: install Node.js explicitly

---

default.json
jsonnet/default.jsonnet

- https://github.com/aquaproj/aqua-renovate-config/pull/917#issuecomment-2881672122

fix: add a packageRule for wash

---

aqua-renovate-config.json
file.json
installer-script.json
jsonnet/aqua-renovate-config.jsonnet
jsonnet/installer-script.jsonnet
jsonnet/utils.libsonnet

- https://github.com/aquaproj/aquaproj.github.io/pull/1582
- https://github.com/aquaproj/aqua-renovate-config/issues/957

fix: enclose arguments with `/` to treat them as regular expressions
